# Generated by Django 4.1.7 on 2023-07-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(default='', upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField()),
                ('price_min', models.FloatField()),
                ('price_max', models.FloatField()),
                ('ram', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.computerbrands')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_code', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField()),
                ('unit_rate', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.computerspecification')),
            ],
        ),
    ]
